# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - init: echo 'init script' # runs during prebuild
    command: |
      python -m venv venv
      source venv/bin/activate
      pip install -r requirements.txt

