version: "3.7"
services:
  postgres:
    image: postgres:12-alpine
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    ports:
      - "5432:5432"
  init:
    image: apache/airflow:2.0.0-python3.8
    depends_on:
      - postgres
    env_file:
      - .env
    entrypoint: /bin/bash
    command: -c 'airflow db upgrade && sleep 5 && airflow users create --username admin --password admin --firstname Anonymous --lastname Admin --role Admin --email admin@example.org'
  webserver:
    image: apache/airflow:2.0.0-python3.8
    restart: always
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    volumes:
      - logs:/opt/airflow/logs
    env_file:
      - .env
    command: webserver
  scheduler:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - postgres
    volumes:
      - ./dags:/opt/airflow/dags
      - logs:/opt/airflow/logs

    env_file:
      - .env
    command: scheduler

volumes:
  logs:
