service: etl-aws-lambda

frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.8
  timeout: 30
  iam:
    role: e
  environment:
    CLEAN_BUCKET_NAME: {}
  

functions:
  hello:
    handler: main.csvtoparquet
    events:
      - s3:
          bucket: {}
          event: s3:ObjectCreated:*
          rules:
            - suffix: .csv
          existing: true
      
    
